name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run-fixtool:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute test suite
        run: dotnet test
